### ISSUE TITLE
Getting a more than one dimension array via OSC

### ISSUE THREAD

**Issue by Sarctiann** [thomas-hermann/sc3nb#12]
Hi, I'm trying to use cmdg method to get the result of [[1,2], [3,4]], for example apparently python-osc can't parse it. If I send the code [1, [1,2], [3,4]] instead. This works fine. I think it's something in the "parse_sclang_blob" function, or it may be in get_*something* from python_osc.parsing, something with the character sequence "[[". Unfortunately I do not have enough knowledge about byte orders, or OSC, to be able to solve it ...
```python3
>>> SERVER.cmdg("[[1,2],[3,4]]")
DEBUG:root:## start parsing bundle: b'#bundle\x00\xe3\x1e\xff\xec\xb6p\xf1\xed\x00\x00\x00\x10\x00\x00\x00\x02,ii\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x10\x00\x00\x00\x02,ii\x00\x00\x00\x00\x03\x00\x00\x00\x04'
DEBUG:root:msg count 108
DEBUG:root:>> parse sc msg: b'\x00\x00\x00\x10\x00\x00\x00\x02,ii\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x10\x00\x00\x00\x02,ii\x00\x00\x00\x00\x03\x00\x00\x00\x04'
DEBUG:root:msg size 16
DEBUG:root:found list
DEBUG:root:[ start parsing list: b'\x00\x00\x00\x02,ii\x00\x00\x00\x00\x01\x00\x00\x00\x02'
DEBUG:root:new value 1
DEBUG:root:new value 2
DEBUG:root:resulting list [1, 2]
DEBUG:root:] end parsing list
DEBUG:root:msgs left 107
DEBUG:root:>> parse sc msg: b'\x00\x00\x00\x10\x00\x00\x00\x02,ii\x00\x00\x00\x00\x03\x00\x00\x00\x04'
DEBUG:root:msg size 16
DEBUG:root:found list
DEBUG:root:[ start parsing list: b'\x00\x00\x00\x02,ii\x00\x00\x00\x00\x03\x00\x00\x00\x04'
DEBUG:root:new value 3
DEBUG:root:new value 4
DEBUG:root:resulting list [3, 4]
DEBUG:root:] end parsing list
DEBUG:root:msgs left 106
DEBUG:root:>> parse sc msg: b''
WARNING:root:Ignoring Exception:
Datagram is too short
returning blob
INFO:root:OSC_COM: osc msg received from sclang: ('/return', b'#bundle\x00\xe3\x1e\xff\xec\xb6p\xf1\xed\x00\x00\x00\x10\x00\x00\x00\x02,ii\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x10\x00\x00\x00\x02,ii\x00\x00\x00\x00\x03\x00\x00\x00\x04')
b'#bundle\x00\xe3\x1e\xff\xec\xb6p\xf1\xed\x00\x00\x00\x10\x00\x00\x00\x02,ii\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x10\x00\x00\x00\x02,ii\x00\x00\x00\x00\x03\x00\x00\x00\x04'
```

**Comment by Sarctiann** [comment]
I'm still trying to find the problem, it may be something in the _parse_bundle function

**Comment by dreinsch** [comment]
Thank you very much for reporting this issue!
We are currently still in the pre-release phase of development and working on the internals.

This problem was fixed in the dev branch with the following commit https://github.com/thomas-hermann/sc3nb/commit/3405e3f2440553634e2b8724c8b914e63d969f97
So please feel free to checkout the dev branch and keep on reporting all issues you find! 

The problem occurred as a result of a change how SuperCollider is sending a nested list. 
This is no data type directly supported by the OSC specification and SuperCollider is sending this data as raw bytes.
We managed to reverse engineer the data structure and parse the content. However it is planned that we reach out to the SuperCollider devs and establish a better documentation and stability of this parsing.
